# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "65d429496ba14fc46cf5dec321399ec3"
name = "Zoro Countdown Timer Bar"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
